import Head from 'next/head'
import Layout from '@/components/Layout'
import ProfilePic from "../../public/images/profile/1.png";
import Image from 'next/image';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
// import styles from './index.css';
export default function Home() {
  return (
    <>
      <Head>
        <title>AnujGaida</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full'></div>
          <div className='w-1/2'>
            <Image src={ProfilePic} alt="AnujGaida" className='w-auto h-auto' />
          </div>
          <div className='w=1/2 flex flex-col items-center self-center'>
            
            <AnimatedText  text="Turning Vision Into Reality With Code And Design."  className='!text-6xl !text-left '/>
            <p style={{ position: "absolute", right: "5rem", top: "60vh", width: "60vw"}} className='my-4 text-base font-medium'>
            Hi, I’m a passionate Computer Engineer, blending technology with creativity to solve real-world challenges. With expertise in AI, Data Science, I craft intelligent solutions that bridge the gap between data and decisions!
            </p>
            <div style={{ position: "absolute", right: "5rem", top: "80vh", width: "60vw"}} className='flex items-center self-start mt-2'>
              <Link href="/dummy.pdf" target={"_blank"}
              className='flex items-center bg-dark text-light p-2.5 px-6
              rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
              border-2 border-solid border-transparent hover:border-dark
              '
              download={true}
              >Resume <LinkArrow className={"w-6 ml-1"}/>
              </Link>
              <Link href="mailto:gaidaanuj@gmail.com" target={"_blank"}
              className='ml-4 text-large font-medium capitalize text-dark'
              
              >contact</Link>
            </div>

          </div>
        </Layout>
      </main>
    </>
  )
}
